/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '31/03/16 21:58' with Gradle 2.2.1
 *
 * @author admin, @date 31/03/16 21:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
